# Generated by Django 5.1.4 on 2026-09-12 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edizione', models.PositiveIntegerField(help_text='1, 2, 3... progressivo nella stagione', verbose_name='numero edizione')),
                ('stagione', models.CharField(default='2025/26', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('data', models.DateField()),
                ('ora', models.TimeField(blank=True, null=True)),
                ('colore_sfondo_1', models.CharField(default='#f6dfa0', max_length=7)),
                ('colore_sfondo_2', models.CharField(default='#f0c96a', max_length=7)),
                ('colore_sfondo_3', models.CharField(default='#eecf8f', max_length=7)),
                ('colore_accento', models.CharField(default='#ffffff', max_length=7)),
                ('nota_programma', models.TextField(blank=True, help_text='Testo introduttivo sul concerto/compositore.', verbose_name='nota di programma')),
                ('prima_esecuzione_tipo', models.CharField(blank=True, choices=[('', 'Nessuna'), ('assoluta', 'Prima esecuzione assoluta'), ('svizzera', 'Prima esecuzione svizzera'), ('nazionale', 'Prima esecuzione nazionale')], default='', max_length=20, verbose_name='prima esecuzione')),
                ('link_prenotazione', models.URLField(blank=True, verbose_name='link prenotazione/biglietteria')),
                ('pubblicato', models.BooleanField(default=False, help_text='Se disattivo, il concerto non è visibile sul sito pubblico.')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'concerto',
                'verbose_name_plural': 'concerti',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ruolo', models.CharField(choices=[('interprete', 'Interprete'), ('regia_audio', 'Regia Audio'), ('compositore', 'Compositore'), ('direzione', 'Direzione artistica')], max_length=20)),
                ('strumento', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('ritratto', models.ImageField(blank=True, null=True, upload_to='ritratti/')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'persone',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('indirizzo', models.CharField(blank=True, max_length=300)),
                ('mappa_url', models.URLField(blank=True, verbose_name='link mappa (Google Maps ecc.)')),
            ],
            options={
                'verbose_name': 'sede',
                'verbose_name_plural': 'sedi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sostenitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='sostenitori/')),
                ('url', models.URLField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'sostenitore',
                'verbose_name_plural': 'sostenitori',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Brano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compositore', models.CharField(max_length=200)),
                ('titolo', models.CharField(max_length=300)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('concerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brani', to='concerti.concerto')),
            ],
            options={
                'verbose_name': 'brano in programma',
                'verbose_name_plural': 'brani in programma',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FotoConcerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='foto_concerti/%Y/%m/')),
                ('didascalia', models.CharField(blank=True, max_length=200)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('concerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='concerti.concerto')),
            ],
            options={
                'verbose_name': 'foto concerto',
                'verbose_name_plural': 'foto concerti',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Partecipazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strumento_in_concerto', models.CharField(blank=True, help_text='Se vuoto, usa lo strumento di default della persona.', max_length=120, verbose_name='strumento/ruolo per questo concerto')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('concerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipazioni', to='concerti.concerto')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipazioni', to='concerti.persona')),
            ],
            options={
                'verbose_name': 'partecipazione',
                'verbose_name_plural': 'partecipazioni',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.AddField(
            model_name='concerto',
            name='persone',
            field=models.ManyToManyField(related_name='concerti', through='concerti.Partecipazione', to='concerti.persona'),
        ),
        migrations.AddField(
            model_name='concerto',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concerti', to='concerti.sede'),
        ),
        migrations.AddConstraint(
            model_name='partecipazione',
            constraint=models.UniqueConstraint(fields=('concerto', 'persona'), name='persona_unica_per_concerto'),
        ),
        migrations.AddConstraint(
            model_name='concerto',
            constraint=models.UniqueConstraint(fields=('stagione', 'numero_edizione'), name='unica_edizione_per_stagione'),
        ),
    ]
