# Generated by Django 5.1.4 on 2026-09-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concerto',
            name='prima_esecuzione_tipo',
        ),
        migrations.AddField(
            model_name='brano',
            name='prima_esecuzione_tipo',
            field=models.CharField(blank=True, choices=[('', 'Nessuna'), ('assoluta', 'Prima esecuzione assoluta'), ('svizzera', 'Prima esecuzione svizzera'), ('nazionale', 'Prima esecuzione nazionale')], default='', max_length=20, verbose_name='prima esecuzione'),
        ),
    ]
