# Generated by Django 5.1.4 on 2026-09-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerti', '0002_remove_concerto_prima_esecuzione_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerto',
            name='nota_programma_de',
            field=models.TextField(blank=True, default='', verbose_name='nota di programma (DE)'),
        ),
        migrations.AddField(
            model_name='concerto',
            name='nota_programma_en',
            field=models.TextField(blank=True, default='', verbose_name='nota di programma (EN)'),
        ),
        migrations.AddField(
            model_name='concerto',
            name='nota_programma_fr',
            field=models.TextField(blank=True, default='', verbose_name='nota di programma (FR)'),
        ),
        migrations.AddField(
            model_name='persona',
            name='bio_de',
            field=models.TextField(blank=True, default='', verbose_name='bio (DE)'),
        ),
        migrations.AddField(
            model_name='persona',
            name='bio_en',
            field=models.TextField(blank=True, default='', verbose_name='bio (EN)'),
        ),
        migrations.AddField(
            model_name='persona',
            name='bio_fr',
            field=models.TextField(blank=True, default='', verbose_name='bio (FR)'),
        ),
    ]
